### ISSUE TITLE
Mejoras al modulo

### ISSUE THREAD

**Issue by nicolasriquelme62** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#10]
Estimados, buenas tardes.

Hemos instalado el modulo en vario clientes y hasta el momento funciona bien. Varios clientes nos solicitan que el modulo incorporé la opción de _**seleccionar el estado del pedido después del pago**_ (pago aceptado, preparación en curso, etc etc). Esta opción la tiene el otro modulo v3.2.0 de webpay.

muchas gracias.

**Comment by msaustral** [comment]
Hola, ya esta publicado, saludos

**Comment by gonzunigad** [comment]
Si, acabamos de publicar. Cerraré el issue :)
