### ISSUE TITLE
Timeout on payment page

### ISSUE THREAD

**Issue by AstroniumGIT** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#11]
On checkout step, where prestashop redirects to the payment page it doesn't load and times out.

1) Pick webpay payment on checkout payment step
2) Wait for payment page to load up

Observed behavior: Webpay page does not load and does not gite any response.
Expected behaviour: Page load up and i perform a test payment

![image](https://user-images.githubusercontent.com/49211917/105520923-f274bb00-5ce3-11eb-8e13-9cbfd3743939.png)
![image](https://user-images.githubusercontent.com/49211917/105521027-0fa98980-5ce4-11eb-9638-726ea5f5ff39.png)

Module configuration is default that comes after installation. Transaction validation in module diagnosis does not give any result too.
![image](https://user-images.githubusercontent.com/49211917/105521993-5a77d100-5ce5-11eb-82d7-0fe005251a37.png)

**Comment by gonzunigad** [comment]
Hi @AstroniumGIT. That is not a problem whit the plug-in itself. You or Transbank is blocking the connection. Where are you located?

**Comment by gonzunigad** [comment]
Try to connect using a VPN from USA or something like that.

**Comment by AstroniumGIT** [comment]
Hi @gonzunigad. Thank you for your quick answer!
I am from Ukraine and VPN helped me to resolve that issue.
Thank you for your help!
