### ISSUE TITLE
Will not follow more than 6 redirects

### ISSUE THREAD

**Issue by cmaureirac** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#25]
Al probar el plugin 1.0.3 de TRansbank para prestashop me aparece el siguiente error:

"Will not follow more than 6 redirects"

Por favor ayuda!

**Comment by devferuz** [comment]
alguna novedad con esto?

**Comment by mastudillot** [comment]
Esto puede ocurrir porque la ip de tu servidor se encuentra bloqueada por Transbank, posiblemente tenga un fraudscore muy alto.
