### ISSUE TITLE
Monto del carro ha cambiado

### ISSUE THREAD

**Issue by kapozar** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#26]
con la versión 1.0.3 a los clientes que compran a través de teléfonos móviles, algunas veces les indica que el monto del carrito de compra ha cambiado y que la transacción no fue realizada..
pude hacer el ejercicio con un cliente que me reporto el error y la compra era valida.. desconozco de que forma se podría alterar el carro de compras para que salte el error

**Comment by ricardo-dota** [comment]
Estimados 

La version del modulo anterior que esta deprecada 3.2.0 tambien tiene un  error similar   que no se si es vulnerabilidad u otro tema

Ejemplo 

Una persona compra un producto por 475.000 , pero en trasnbank aparece que el monto de la venta autorizada  es de 26.900

**Comment by mastudillot** [comment]
Esto ocurre cuando una persona tiene abierta una pestaña mientras realiza el pago en transbank y en otra pestaña añade productos al carro de compra.  Es una protección para evitar que puedan añadir más productos cuando se esta realizando el pago del carro.
