### ISSUE TITLE
Modulo no permite guardar configuración

### ISSUE THREAD

**Issue by smancinih** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#27]
Al momento de configurar el modulo no aparece la opcion de guardar la configuración

al momento de instalar una instancia del modulo, este no muesta el boton de "guardar" presente en la documentación. Ademas al instalarlo aparece ya con credenciales llenando los datos, que no corresponden a nuestro comercio.

![image](https://user-images.githubusercontent.com/93737913/140413104-5e8fb6bf-07f7-4c17-87be-1a06e77e397e.png)

- Plugin: 1.0.3
- Prestashop: 1.7.6.9
- PHP: 7.2.34

**Comment by mastudillot** [comment]
La opción se encuentra tapada por el mensaje de configuración cuando se tiene habilitado multitienda.

**Comment by msaustral** [comment]
Hola, esto sucede porque tienes la función multi tienda de Prestashop activada, no se si el módulo sea compatible con esta función, saludos
