### ISSUE TITLE
Estado "Error de pago" en Prestashop 1.7.8.0 con compras pagadas correctamente

### ISSUE THREAD

**Issue by a-suez** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#28]
Al actualizar a la versión 1.7.8.0 de Prestashop, las compras con pagos validos se registran en prestashop en estado "Error de pago"

Una descripción concisa sobre el bug.

**Para reproducir**

1. Actualizar a prestashop 1.7.8.0
2. Realizar una compra de manera normal
3. Ir al listado de ordenes
4. Se ven las compras con pago validado en estado "error de pago"

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/80276471/141145617-35cd094b-cd92-4d26-ab7b-31c68490e6bb.png)

![image](https://user-images.githubusercontent.com/80276471/141145939-4db9013f-1770-433c-a95a-17fbc6da2cf9.png)

![image](https://user-images.githubusercontent.com/80276471/141146069-b5e5bb68-868c-4399-8705-0e58b62d7990.png)

Prestashop
Version E-commerce: | 1.7.8.0
Versión del plugin instalada: | 1.0.3
Última versión del plugin disponible: | v1.0.3
Estado de la Extensiones de PHP
Información Principal
 Software Servidor:	Apache
PHP
Estado de PHP	OK
Versión instalada: :	7.2.34
Extensiones PHP requeridas
Extensión	Estado	Versión
openssl	OK	OpenSSL 1.1.1d 10 Sep 2019
SimpleXml	OK	7.2.34
dom	OK	20031129

Favor su ayuda para poder actualizar a 1.7.8.0

**Comment by Dalfaro1984** [comment]
Hola buenas tardes, ¿logró solucionar el problema?

**Comment by jorgejsr** [comment]
Hola, buenas noches, algun comentario respecto del error reportado??

**Comment by gunnerschile** [comment]
@jorgejsr Por lo que me indicaron en el slack de transbank es un error de prestashop.

La solución que me dieron es esta: Si tienes acceso a la BD, ve a la tabla ps_order_state y modifica la columna logable para los registros con id 2 y 3 los dejas con valor 0   . Con eso se me solucionó

**Comment by jorgejsr** [comment]
@gunnerschile Muchas gracias, funciono a la perfección

**Comment by gbaeza15** [comment]
> @jorgejsr Por lo que me indicaron en el slack de transbank es un error de prestashop.
> 
> La solución que me dieron es esta: Si tienes acceso a la BD, ve a la tabla ps_order_state y modifica la columna logable para los registros con id 2 y 3 los dejas con valor 0 . Con eso se me solucionó

Hola, mismo problema en PS 1.7.8.1 y PHP 7.4.26.

No veo cómo eso puede ser una solución. Al hacerlo, estamos modificando la opción "considerar el pedido asociado como validado" de los estados "Pago aceptado" y "Preparación en proceso"... me parece que no hay que tomarlo tan a la ligera considerando que uno normalmente tiene otros medios de pago e historial de pedidos.

**Comment by a-suez** [comment]
Gracias por sus respuestas!

**Comment by serviciopyme** [comment]
> @jorgejsr Por lo que me indicaron en el slack de transbank es un error de prestashop.
> 
> La solución que me dieron es esta: Si tienes acceso a la BD, ve a la tabla ps_order_state y modifica la columna logable para los registros con id 2 y 3 los dejas con valor 0 . Con eso se me solucionó

No tengo ningún registro con campos logable 2 o 3, todos son 0 o 1.
Alguien mas pudo solucionarlo?

![Captura de Pantalla 2021-12-03 a la(s) 02 31 20](https://user-images.githubusercontent.com/95462716/144550682-deca0a64-f8bd-445c-8728-a8a66866ac06.png)

**Comment by gunnerschile** [comment]
@serviciopyme   

Verifica de forma manual

![image](https://user-images.githubusercontent.com/44899807/144552188-92f28109-45f1-4e3d-96d3-4dbc17a31028.png)

**Comment by gbaeza15** [comment]
> > @jorgejsr Por lo que me indicaron en el slack de transbank es un error de prestashop.
> > La solución que me dieron es esta: Si tienes acceso a la BD, ve a la tabla ps_order_state y modifica la columna logable para los registros con id 2 y 3 los dejas con valor 0 . Con eso se me solucionó
> 
> No tengo ningún registro con campos logable 2 o 3, todos son 0 o 1. Alguien mas pudo solucionarlo?
> 
> ![Captura de Pantalla 2021-12-03 a la(s) 02 31 20](https://user-images.githubusercontent.com/95462716/144550682-deca0a64-f8bd-445c-8728-a8a66866ac06.png)

Son los id_order_state 2 y 3, los logables siempre tienen valores 0 ó 1.

**Comment by mastudillot** [comment]
Por favor revisar bien el cambio antes de utilizarlo en producción, si alguien vende productos digitales, que nos confirme si no hay problemas con alguna lógica que pueda tener implementada, el release de la versión quedo detenido ante una posible corrección por parte de Prestashop

**Comment by aaristegui** [comment]
Por acá con el mismo problema con PS 1.7.8.2. Agradecería si hay nueva información

**Comment by msaustral** [comment]
Hola buenos días, esto se puede deber a que modificaron los ID asignados a los estados en la configuración de Prestashop.

Cuando se desarrolló el módulo se asignó de forma estática el id de los estados, 
- id 2 -> PAgo Aceptado 
- id 3 -> Preparación en curso

qué son los id asignados a estos estados de fabrica.

Validen que los ID pertenezcan a cada estado en su instalación de Prestashop, saludos

**Comment by aaristegui** [comment]
> Hola buenos días, esto se puede deber a que modificaron los ID asignados a los estados en la configuración de Prestashop.
> 
> Cuando se desarrolló el módulo se asignó de forma estática el id de los estados,
> 
> * id 2 -> PAgo Aceptado
> * id 3 -> Preparación en curso
> 
> qué son los id asignados a estos estados de fabrica.
> 
> Validen que los ID pertenezcan a cada estado en su instalación de Prestashop, saludos

No hemos modificado los estados de Prestashop, es más, son los siguientes:

-  2 Pago Aceptado
-  3 Preparación en curso
-  8 Error en pago.

Saludos

**Comment by msaustral** [comment]
Hola @aaristegui valida en la tabla config de prestashop el campo WEBPAY_DEFAULT_ORDER_STATE_ID_AFTER_PAYMENT que tenga como valor 2 o 3

Saludos

**Comment by aaristegui** [comment]
Muchas gracias @msaustral, tenemos esa tabla con el valor 3. 

Saludos

**Comment by msaustral** [comment]
Hola valida también el campo PS_OS_PREPARATION en la misma tabla, debe tener valor 3

También busca en la tabla xx_webpay_rest_transactions el pedido y valida: 

- que el campo buyOrder tiene el id del carro del pedido 
- el campo response debe ser igual a 0 
- campo token, session tengan valor  
- status sea 4

Valida que tenga un certificado SSL válido y el api key esté configurado en producción en la configuración del módulo

Saludos

**Comment by pesquerra** [comment]
Hola, hay alguna novedad sobre este problema? yo tengo el error pero no he revisado a profundidad solo se que pasa con montos mayores a 1000 entonces no me cuadra mucho eso de los estados, no creo que el problema venga por ahí, solo especulo porque como dije no he revisado a profundidad.

Saludos.

**Comment by mastudillot** [comment]
La solución va por el lado de Prestashop, puedes apoyar dando tus comentarios en los hilos del siguiente PR https://github.com/PrestaShop/PrestaShop/pull/26824 o en la incidencia creada https://github.com/PrestaShop/PrestaShop/issues/26553

**Comment by pesquerra** [comment]
Esta solución temporal me funcionó:
Archivo:  config.inc.php

/**
 * @deprecated since 1.7.7
 */
define('_PS_PRICE_COMPUTE_PRECISION_', 0);

Saludos.

**Comment by msaustral** [comment]
Hola esta es otra forma de resolver: https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/issues/37

Recomendamos aplicarlo en el módulo webpay para evitar que dependa de la versión de Prestashop que se use, saludos

**Comment by pesquerra** [comment]
> 

Hola, hice una prueba y no funciono, igual queda con "Error en pago".

**Comment by a-suez** [comment]
> > 
> 
> Hola, hice una prueba con la solución #37y no me funciono, igual queda con "Error en pago", así que sigo usando la de 'PS_PRICE_COMPUTE_PRECISION' que me funciona sin problema para "pago aceptado" y "preparación en curso". Saludos.

Hola @pesquerra por favor, ¿podrías decirme como implementar la solución 'PS_PRICE_COMPUTE_PRECISION' que mencionas?

Gracias!

**Comment by raulito12** [comment]
Hola, tengo el mismo problema, mis clientes hacen el pago por webpay y cuando voy a ver pedido en backoffice de prestashop 1.7.8.3  sale ERROR DE PAGO, pero con montos menos a 1000 sale PAGO ACEPTADO ayuda porfavor

**Comment by gunnerschile** [comment]
> @raulito12 

Me pasaba lo mismo con la nueva versión de Transbank, así que me volví a la v1.0.3 con los cambios que mencioné al inicio del hilo...haciendo el backup completo del sitio previamente

**Comment by raulito12** [comment]
@gunnerschile 
gracias por responder, cuando mis clientes hacen el pago, en el backoffice de prestashop Me sale ERROR DE PAGO, verifico mi cuenta y no hay ningún depósito por ende pierdo un pedido importante. hice una prueba y me sale los siguientes pantallazos. gracias por la ayuda.
![anexo05](https://user-images.githubusercontent.com/63971024/159143662-e763333c-5e03-4555-868e-30e3e930676d.png)
![anexo07](https://user-images.githubusercontent.com/63971024/159143663-0676fef3-0da7-43be-8516-6cc39853b8a1.png)

**Comment by raulito12** [comment]
creo que es porque actualicé mi prestashop a 1.7.8.3, finalmente crees que sería una buena opción desinstalar el módulo webpay y buscar otro módulo de pasarela de pagos? gracias

**Comment by gunnerschile** [comment]
@raulito12 estoy con prestashop 1.7.8.5 y no tengo el problema, almenos con la versión de modulo 1.0.3 y los cambios que realice hace uno o dos meses

![image](https://user-images.githubusercontent.com/44899807/159144084-45e7d467-cd40-42c5-b878-d72307b72a65.png)

**Comment by raulito12** [comment]
mi estimado @gunnerschile 
cuando dice versión de modulo 1.0.3 se refiere al módulo de webpay verdad? en mi caso tengo la versión 1.1.1 de mi webpay, así me sale como en el anexo adjunto, donde puedo encontrar la versión más acutal quizás eso sea mi problema. ud que dice? gracia
![ane01](https://user-images.githubusercontent.com/63971024/159144470-cbe3c25d-2fe5-420d-8b3b-f2c8f81463bc.png)
s

**Comment by gunnerschile** [comment]
@raulito12 Si, me refiero a la versión del modulo de webpay. Es posible que pueda ser ese el problema, almenos yo decidí no actualizar a la versión v1.1.x debido a los problemas que mencionaron otros usuarios y me quede en la versión 1.0.3.
La versión actual es la v1.1.1 que tienes instalada, yo estoy con una versión anterior.

**Comment by gunnerschile** [comment]
> @raulito12 Si, me refiero a la versión del modulo de webpay. Es posible que pueda ser ese el problema, almenos yo decidí no actualizar a la versión v1.1.x debido a los problemas que mencionaron otros usuarios y me quede en la versión 1.0.3. La versión actual es la v1.1.1 que tienes instalada, yo estoy con una versión anterior.

![image](https://user-images.githubusercontent.com/44899807/159144618-cf9cd4b3-755b-4417-8294-dbd885a16a6b.png)

**Comment by raulito12** [comment]
@gunnerschile porfavor me puede compartir ese módulo? o el link donde lo consigo mil gracias

**Comment by gunnerschile** [comment]
@raulito12 https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/releases/download/v1.0.3/plugin-prestashop-webpay-rest-v1.0.3.zip  ese es el link, está en las descargas.

Si realizas algún cambio, recomiendo que hagas una copia completa de tu sitio antes de modificarlo, incluida la bd... yo almenos lo hago vía softaculous. Adicional al cambio de versión, tendrías que hacer el cambio a nivel de base de datos que comenté mas arriba (solución que a mi me sirvió en producción por lo menos, no se el resto)

**Comment by raulito12** [comment]
Gracias amigo lo pondré en marcha y te comento

**Comment by raulito12** [comment]
@gunnerschile Hola mi estimado
Te comento que aún no puedo solucionarlo. instalé la webpay 1.1.3 y sigue el error pero despues de muchas purebas me percato que solo ocurre con mentos mayores a 1.000, con montos inferiores todo anda correcto como en la imagen adjunto, espero que me puedas dar alguna otra pista para seguir con esta batalla amigo.

![a01](https://user-images.githubusercontent.com/63971024/159191640-9771dfb3-6ce9-4fb5-85fb-43e2fefd949e.png)

![A02](https://user-images.githubusercontent.com/63971024/159191641-2b2eb093-9ccc-45e7-9f89-ca543c7c28f3.png)

**Comment by gunnerschile** [comment]
@raulito12 hablame al correo andres.basoalto@webredes.cl y veo como ayudarte mas rapido.

**Comment by raulito12** [comment]
te escribi

**Comment by raulito12** [comment]
@gunnerschile te escribí al correo amigo

**Comment by pesquerra** [comment]
Yo he puesto en funcionamiento varias tiendas con el el modulo de Webpay 1.1.1 y funciona sin problema haciendo el cambio yo mismo publique hace un tiempo de los decimales en el archivo **config.inc.php**.

Deben buscar y editar el archivo **public_html/config/config.inc.php**
Buscan la línea **define('_PS_PRICE_DISPLAY_PRECISION_', 2);**
y la dejan así: **define('_PS_PRICE_COMPUTE_PRECISION_', 0);**

Saludos.

**Comment by mastudillot** [comment]
Hola a todos, aquí se mencionan algunas soluciones temporales, pero recuerden que la solución final va por el lado de prestashop.

**Comment by msaustral** [comment]
Hola @raulito12 @gunnerschile buen día, no se recomienda usar una versión que no sea la ultima ya que esta evita un procedimiento de estafa que están aplicando en varias plataformas, donde el pedido y el pago tienen montos distintos, saludos

**Comment by hansscd** [comment]
Muchas gracias por toda la ayuda. 
Revisando hoy vi que Prestashop ya acepto y corrigió el código del error, por lo que debería quedar solucionado en su próxima actualización 1.7.8.6. 
Habrá que esperar a que la liberen.

**Comment by msaustral** [comment]
Hola, también pueden aplicar este cambio en el módulo de TB, de esta forma quitamos la dependencia de la Versión que pueda tener el cliente que la usa.

Para corregir el error hay que cambiar la línea 146 del archivo validate.php que está en modules/webpay/controllers/front

De esto: if ($webpayTransaction->amount != $amount) {
A esto: if ($webpayTransaction->amount != round($amount)) {

**Comment by mastudillot** [comment]
como comenta @hansscd esto se va a solucionar en la versión de prestashop  1.7.8.6, esto no requerirá cambios adicionales en el plugin, por lo que solo deberían actualizar su versión de prestashop

**Comment by msaustral** [comment]
Hola @mastudillot tomar en cuenta que migrar de versión el Prestashop no es tan fácil y en muchas ocasiones no la mejor opción.

Al actualizar, siempre hay módulos, funciones y partes de las plantillas que dejan de funcionar.

Ejemplo, ya no funcionan los override de clases en las últimas versiones.
