### ISSUE TITLE
Error Webpay V1.1.0 Prestashop 1.7.6.8

### ISSUE THREAD

**Issue by ivaldes2786** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#34]
Actualice la ultima versión de Webpay y ya no se pueden realizar pagos.

**Para reproducir**

1. Instalar Webpay 1.1.0 en Prestashop 1.7.6 (desconozco si en otras versiones aparece el problema)
2. Iniciar una compra
3. Dar clic en pagar. La pagina de confirmación arroja un error
4. Tambien se puede ver el error en realizando el diagnostico en el Back Office

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/25473464/146710072-27b61d3b-0a12-4b88-8c04-399023eda450.png)

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 1.1.0
- Prestashop: 1.7.6.8
- PHP: 7.3

Agradecería su ayuda.
Saludos

**Comment by AlexisFAR** [comment]
Hola, si es la versión del plugin, utilizando Prestashop 1.7.6.8 me sucede lo mismo. Tengo un respaldo de versión 1.0.3 y funciona ok.

**Comment by ricardo-dota** [comment]
Hola

Llame a transbank en el área de integración  los cuales me generaron una nueva secret-key ,pero igualmente no logra conectarse al servicio e internamente enviaron una solicitud interna del problema

prestashop 1.7.6

**Comment by ricardo-dota** [comment]
Gracias en la version 1.1.1 esta solucionado, creo que pueden cerrar el tema

**Comment by mastudillot** [comment]
Solucionado en la versión 1.1.1 del plugin
