### ISSUE TITLE
El monto del carro ha cambiado

### ISSUE THREAD

**Issue by msaustral** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#37]
Hola a todos, se está presentando mucho que el módulo de Transbank dispara el validador de carrito por ERROR, mostrando el mensaje "El monto del carro ha cambiado......" al clientes.

Esto se debe a que la función que usa el módulo Webypay, getOrderTotal(true, Cart::BOTH), que es nativa de Prestashop, tiene un error en algunas versiones de Prestashop (Hasta el momento identificada en la 1.7.6.8), donde busca en la configuración de Prestashop la cantidad de decimales a mostrar, pero ese campo ya no existe, ERROR de PRESTASHOP, ya corregidos en nuevas versiones.

Esto lo que causa es que el módulo Transbank compare 10001 contra 10000,89, al no ser el mismo monto dispara el validador y el pedido no se procesa.

Para corregir el error hay que cambiar la línea 146 del archivo validate.php que está en modules/webpay/controllers/front

De esto: if ($webpayTransaction->amount != $amount) {
A esto: if ($webpayTransaction->amount != round($amount)) {

Saludos

**Comment by mastudillot** [comment]
Muchas gracias, vamos a revisar lo que comentas y lo integraremos en la siguiente versión

**Comment by pesquerra** [comment]
> Hola a todos, se está presentando mucho que el módulo de Transbank dispara el validador de carrito por ERROR, mostrando el mensaje "El monto del carro ha cambiado......" al clientes.
> 
> Esto se debe a que la función que usa el módulo Webypay, getOrderTotal(true, Cart::BOTH), que es nativa de Prestashop, tiene un error en algunas versiones de Prestashop (Hasta el momento identificada en la 1.7.6.8), donde busca en la configuración de Prestashop la cantidad de decimales a mostrar, pero ese campo ya no existe, ERROR de PRESTASHOP, ya corregidos en nuevas versiones.
> 
> Esto lo que causa es que el módulo Transbank compare 10001 contra 10000,89, al no ser el mismo monto dispara el validador y el pedido no se procesa.
> 
> Para corregir el error hay que cambiar la línea 146 del archivo validate.php que está en modules/webpay/controllers/front
> 
> De esto: if ($webpayTransaction->amount != $amount) { A esto: if ($webpayTransaction->amount != round($amount)) {
> 
> Saludos

Hola, hice una prueba y no funciono, igual queda con "Error en pago".

**Comment by mvarlic** [comment]
muchas gracias @msaustral quedo corregido en la version 1.1.2
