### ISSUE TITLE
Errores al instalar master branch del 29-12-21

### ISSUE THREAD

**Issue by msaustral** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#38]
Hola al tratar de instalar la versión mas reciente da los siguientes errores:

- error en el archivo  libwebpay -> TransbankSdkWebpay.php línea 3 ya que falta la carpeta vendor en la raíz (webpay)
- 'DEFAULT_COMMERCE_CODE' Undefined en línea 477 de webpay.php no logro dar con la falla

**Comment by mastudillot** [comment]
Hola, ¿estas instalando con el zip que se encuentra en los release?

**Comment by msaustral** [comment]
Hola, baje el que esta en master de Git y comprimí la carpeta webpay

**Comment by mastudillot** [comment]
Debes usar el zip que se encuentra en los release, por eso te da error, te dejo el [link](https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/releases/tag/1.1.1),  el archivo es el plugin-prestashop-webpay-rest-1.1.1.zip

**Comment by msaustral** [comment]
Hola si, pero igual estaría faltando la carpeta vendor aquí, saludos

**Comment by mastudillot** [comment]
El zip que te menciono si tiene la carpeta vendor, descarga el archivo y instala el plugin normalmente, debería funcionar sin problemas

**Comment by mastudillot** [comment]
Me comentas si logras solucionar, para poder cerrar en caso de ser necesario 😄

**Comment by mastudillot** [comment]
Te comento también que tenemos una comunidad en slack, donde puedes dejar tus mensajes y podremos atenderte de mejor manera, te dejo el link para que puedas recibir la invitación https://join-transbankdevelopers-slack.herokuapp.com/

**Comment by msaustral** [comment]
Hola, si, lo descargue y funciono, pero si hacemos un fork del master, este no funcionará, saludos

**Comment by mastudillot** [comment]
Claro, porque en master solo se encuentra el código, la carpeta vendor no se sube, y tenemos un proceso automático que genera el zip y agrega la carpeta vendor. Voy a cerrar la incidencia por ahora.
