### ISSUE TITLE
Payment Error - Pago procesado

### ISSUE THREAD

**Issue by valfonso3** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#45]
Buenas, tengo un problema con el módulo de transbank, las compras se realizan, los pagos se procesan pero dentro de la tienda siempre me aparece que el pago tuvo error y tengo que entrar, aceptar el pago y asi con cada venta que se realiza

Habrá alguien con el mismo problema o sabrá como resolver esto?

**Comment by msaustral** [comment]
Hola, la solución en el siguiente caso: https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/issues/39
