### ISSUE TITLE
Attempted to call an undefined method named "chooseHandler" of class "GuzzleHttp\Utils".

### ISSUE THREAD

**Issue by llucerob** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#48]
error al intentar configurar el plugin en prestashop 1.8

<img width="832" alt="Captura de pantalla_20230118_162723" src="https://user-images.githubusercontent.com/29238779/213276035-53fed9f0-030e-46d8-abd7-ca77c69704fb.png">
<img width="816" alt="Captura de pantalla_20230118_162740" src="https://user-images.githubusercontent.com/29238779/213276040-1fcd4b78-de8a-40bd-b403-ada0d8bcdbeb.png">

**Comment by felipesml** [comment]
Mismo error al termina de instalar y entrar a su configuración en Prestashop versión 8.0.1

**Comment by victordonoso** [comment]
No hay solución para esto?

**Comment by Murdrek** [comment]
Hola, tengo el mismo problema con prestashop 8.1.0. al intentar configurar me arroja este error 

Attempted to call an undefined method named "chooseHandler" of class "GuzzleHttp\Utils".

el tema es que me boto por completo el acceso a la configuración de los módulos de prestashop.

favor su respuesta pronto a esta problemática

**Comment by diegoarmando91** [comment]
Hola, a todos, yo también estoy con el mismo problema con el siguiente ambiente:

- Prestashop 8.1.0 estable
- PHP 8.1

 y revisando logs, al parecer el problema está en la dependencia de Guzzle dado a que el plugin utiliza la V5 (Según compose.json), la cual no es compatible con php8 según la documentación de Guzzle. (Ver Tabla)
 
![image](https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/assets/36238275/7061ada3-00e0-4f25-a85c-77b138221c4d)

Revisare si solo actualizando la dependencia se soluciona el error. Les comento si logro resolverlo.

**Comment by diegoarmando91** [comment]
Hola, les cuento avances, actualice la las dependencias (me costó mucho, estoy algo oxidado jaja) pero ahora tengo el siguiente error en la Linea 27 en modules/webpay/src/Controller/Admin/ConfigureController.php

$webpayPlusFormDataHandler = $this->get('webpay.form.webpay_plus_form_data_handler');

Soy bastante nuevo con symfony por lo cual aquí agradecería la ayuda, en que debo fijarme con el fin de detectar y corregir,

![image](https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/assets/36238275/b685e166-3f25-4d78-b4f2-ccb5c10773a8)

**Comment by leonardomlisboa** [comment]
Hola, llamé a transbank y también he tratado de solucionar este inconveniente y no lo logré.- 
Finalmente la solución brindada por transbank es bajar a la versión prestashop 1.7 ya que la versión webpay-rest-2.0.3 no es compatible aún con la versión prestashop 1.8.

Si alguien pudo solucionarlo, agradecería la ayuda, ya que no tenía intención de bajar la versión de prestashop.

Gracias!

**Comment by diegoarmando91** [comment]
Hola, ya por lo mucho que estuve revisando existen varias incompatibilidades dado a que desde PS 8.0 en adelante, esta con una versión más actualizada de Symfony (4.4+) por lo cual cambiaron varias cosas las cuales ya no son compatibles. Toca rearmar el plugin para que funciones.

**Comment by brokercl** [comment]
mismo problema
prestashop 1.8, plugin transbank incompatible

**Comment by alvaroleon** [comment]
Mismo problema! :( espero que puedan actualizar luego el plugin

**Comment by rodrigowilliamson** [comment]
mismo problema

**Comment by marieFuentealba** [comment]
Hola tengo el mismo problema y no puedo ingresar al backoffice para eliminar el modulo, ayuda por favor

**Comment by brokercl** [comment]
no recuerdo bien, pero si es prestashop, baja la version prestashop
saludos
Andres Abalos
Ingeniero Informático y Corredor de Seguros.

**Comment by marieFuentealba** [comment]
Gracias brokercl !! por la recomendación, pero ya compré el template para la versión 8, intentare eliminar el modulo y buscar otra pasarela de pago

**Comment by mastudillot** [comment]
Hola, en la versión [2.1.0](https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/releases/tag/2.1.0) se agregó compatibilidad para Prestashop 8
