### ISSUE TITLE
Unable to generate a URL for the named route "ps_controller_webpay_configure" as such route does not exist.

### ISSUE THREAD

**Issue by sergioaraos** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#62]
Tras varios intentos de instalación, se logra instalar y activar. Pero al intentar configurar, la aplicación muestra este error.

1. Hacer clic en Configurar (luego de instalar y activar)

Hubo también errores al instalar. 

Una explicación concisa y clara de qué es lo que esperas que ocurra.

![image](https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/assets/64826895/6483d14f-85c3-4f23-bbb0-3c387b4c62d9)

- Plugin: Webpay_rest
- Prestashop: 8.0.4
- PHP: 7.4 / 8.2

Agrega cualquier otro información sobre el problema aquí.

**Comment by sergioaraos** [comment]
Cuando tratamos de instalar, aparece este error.

"Se ha producido un error al instalar el módulo webpay. Hook with the name displayPayment has been registered by WebPay, but the corresponding method hookDisplayPayment has not been defined in the Module class."

![image](https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/assets/64826895/1ac89286-e988-4ce5-a94f-32ec09c0ee95)

**Comment by sergioaraos** [comment]
En la versión 1.7.8.9 el módulo trabaja correctamente. Al actualizar a la versión 8.0 o superior aparecen estos errores. Por favor, indicar que aún no es compatible con PS 1.8

**Comment by sergioaraos** [comment]
No he probado el Docker, pero aparentemente el plugin tiene algún problema en la configuración o al instalar. En todas las  pruebas existía el módulo webpay 1.1.3 y funciona sin problemas en la versión 8

**Comment by cluttgue** [comment]
¿Tienen tiempo de resolución?, acabo de instalar y tuve que desactivar todo a mano ya que "bloquea" el panel de administración.

**Comment by eahumad** [comment]
Estoy utilizando prestashop 1.7.8.8 y tengo el mismo problema, debo dejar permanentemente activado el modo debug para acceder al panel de administración

**Comment by kateclaudio** [comment]
Describe el bug

Instalación de paquete Modulo Webpay
Unable to generate a URL for the named route "ps_controller_webpay_configure" as such route does not exist.

Para reproducir

Instalación de paquete en "Gestor de Modulos"
Instala correctamente
Se activa modo Debug
Se bloquea Backoffice "Unable to generate a URL for the named route "ps_controller_webpay_configure" as such route does not exist."
Comportamiento observado

Error 500- No se puede acceder al BackOffice

Capturas de pantalla

Si aplica, agrega aquí capturas de pantalla que ayuden a explicar tu problema.

Versiones (por favor agrega aquí la siguiente información):

Plugin: plugin-prestashop-webpay-rest-2.0.3
Prestashop: 1.7.8.9
PHP 7.4 (ea-php74)
--
[Unable to generate a URL for the named ...not exist.pdf](https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/files/12294093/Unable.to.generate.a.URL.for.the.named.not.exist.pdf)

**Comment by mastudillot** [comment]
Se ha generado la versión [2.1.0](https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/releases/tag/2.1.0) compatible con Prestashop 8
