### ISSUE TITLE
Unable to generate a URL for the named route "ps_controller_webpay_configure" as such route does not exist.

### ISSUE THREAD

**Issue by kateclaudio** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#69]
**Describe el bug**

Instalación de paquete Modulo Webpay
Unable to generate a URL for the named route "ps_controller_webpay_configure" as such route does not exist.

**Para reproducir**

1. Instalación de paquete en "Gestor de Modulos"
2. Instala correctamente
3. Se activa modo Debug
4. Se bloquea Backoffice "Unable to generate a URL for the named route "ps_controller_webpay_configure" as such route does not exist."

**Comportamiento observado**

Error 500- No se puede acceder al BackOffice

**Capturas de pantalla**

Si aplica, agrega aquí capturas de pantalla que ayuden a explicar tu problema.

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: plugin-prestashop-webpay-rest-2.0.3
- Prestashop: 1.7.8.9
- PHP 7.4 (ea-php74)
--

[Unable to generate a URL for the named ...not exist.pdf](https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/files/12294093/Unable.to.generate.a.URL.for.the.named.not.exist.pdf)

**Comment by BetsyMGKL** [comment]
Me pasa lo mismo en Prestashop 8.1. Ha sido imposible instalar el plugin Transbank

**Comment by stivenxd** [comment]
Presento el mismo problema.  En prestashop 8.0.0

**Comment by kateclaudio** [comment]
¡Hola! yo he solucionado este error borrando el caché manualmente desde el administrador de archivos.

**Comment by stivenxd** [comment]
> ¡Hola! yo he solucionado este error borrando el caché manualmente desde el administrador de archivos.

He hecho lo mismo y el error persiste.

**Comment by LEOMARINO** [comment]
Hola, alguna solucion a esto? No me bloquea el backoffice pero si me notifica el error

**Comment by mastudillot** [comment]
Se ha generado la versión [2.1.0](https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/releases/tag/2.1.0) compatible con Prestashop 8
