### ISSUE TITLE
Propuesta de mejora

### ISSUE THREAD

**Issue by elclay7** [TransbankDevelopers/transbank-plugin-prestashop-webpay-rest#8]
El plugin me ha funcionado bastante bien, no he tenido ningún inconveniente.
Pero creo que se pudiera agregar la opción que cuando el cliente realice el pago y este sea exitoso el estatus del pedido en prestashop quede como **pago aceptado** y no como **preparación en curso** ya que se presta para confusión, además pago aceptado es el estado más acertado desde mi punto de vista.

La posibilidad de elegir el estatus cuando la transacción era exitosa estaba disponible en la versión anterior del plugin
![image](https://user-images.githubusercontent.com/13406685/103707178-f4711700-4f8c-11eb-86e1-916b5a746b54.png)

Espero puedan volver a incluirla.

Saludos.

**Comment by gonzunigad** [comment]
Hola @elclay7. Gracias por tu propuesta 🎉 . 
Vamos a analizar la posibilidad de agregarlo. De momento lo eliminamos para simplificar el proceso de configuración, y personalmente no creo que sea el medio de pago donde se deba configurar eso, pero buscando mas profundamente parece ser que efectivamente el medio de pago es el lugar donde se debería hacer. ¿Cómo lo haces con otros medios de pago? No he visto nigún otro que te permita cambiar eso.

**Comment by elclay7** [comment]
> Hola @elclay7. Gracias por tu propuesta 🎉 .
> Vamos a analizar la posibilidad de agregarlo. De momento lo eliminamos para simplificar el proceso de configuración, y personalmente no creo que sea el medio de pago donde se deba configurar eso, pero buscando mas profundamente parece ser que efectivamente el medio de pago es el lugar donde se debería hacer. ¿Cómo lo haces con otros medios de pago? No he visto nigún otro que te permita cambiar eso.

Tengo Mercado Pago y este genera unos estatus personalizados cosa que particularmente no me gusta.
Tambien acepto transferencias bancarias y cuando se realiza una compra por este medio queda en estatus **En espera de pago por transferencia bancaria** luego se valida y se cambia al estatus que amerite. En el caso del plugin de transbank utiliza los estatus por defectos que trae el Prestashop (bien ahi!) con la particularidad que te comente del estatus **preparación en curso**

**Comment by gonzunigad** [comment]
El PR de @msaustral soluciona esto y ya está mezclado. Saldrá en la versión 1.1 ahora pronto.
